version: '3.6'
services:
 back:
  image: mareknowak98/library-backend
  container_name: library-backend
  ports:
   - 5000:5000
  networks:
   - frontback

 front:
  image: mareknowak98/library-frontend
  container_name: library-frontend
  ports:
   - 8080:8080
  depends_on:
   - back
  networks:
   - frontback

networks:
 frontback:
  driver: bridge